services:
  postgres:
    image: postgres:17
    container_name: db-write
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    ports:
      - "5343:5432"
    volumes:
      - pgdata_write:/var/lib/postgresql/data

volumes:
  pgdata_write:
